version: '3.8'

services:
  app:
    build: .
    container_name: instagram_bot
    restart: unless-stopped
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - ./logs:/app/logs
      - ./backup:/app/backup
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - TZ=Asia/Tehran
    depends_on:
      - postgres
    networks:
      - instagram-bot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    # اجرای برنامه اصلی با تاخیر برای اطمینان از آماده بودن دیتابیس
    command: >
      bash -c "
        sleep 15 &&
        python -m app.models.database && 
        python db_recovery.py & 
        uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:14-alpine
    container_name: instagram_bot_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-instagrambot}
      - TZ=Asia/Tehran
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backup:/backup
    ports:
      - "5432:5432"
    networks:
      - instagram-bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    # تنظیمات بهینه‌سازی شده ساده‌تر برای PostgreSQL
    command: postgres -c shared_buffers=128MB -c max_connections=50

  # سرویس ساده‌تر برای پشتیبان‌گیری
  backup:
    image: postgres:14-alpine
    container_name: postgres_backup
    restart: always
    volumes:
      - ./backup:/backup
    environment:
      - PGHOST=postgres
      - PGUSER=${DB_USER:-postgres}
      - PGPASSWORD=${DB_PASSWORD:-postgres}
      - PGDATABASE=${DB_NAME:-instagrambot}
      - TZ=Asia/Tehran
    depends_on:
      - postgres
    networks:
      - instagram-bot-network
    # اجرای اسکریپت پشتیبان‌گیری ساده با cron
    command: >
      bash -c "
        echo '0 */12 * * * pg_dump -h postgres -U ${DB_USER:-postgres} ${DB_NAME:-instagrambot} -f /backup/instagram_bot_`date +\%Y\%m\%d_\%H\%M\%S`.sql && echo \"Backup completed at `date`\" > /backup/last_backup.log' > /var/spool/cron/crontabs/root &&
        echo 'Database backup service running...' &&
        crond -f -d 8"

networks:
  instagram-bot-network:
    driver: bridge

volumes:
  postgres_data:
    name: instagram_bot_postgres_data