version: '3.8'

services:
  app:
    build: .
    container_name: instagram_bot
    restart: always
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - instagram-bot-network
    # ایجاد تاخیر بیشتر برای اطمینان از آماده بودن دیتابیس
    command: >
      bash -c "sleep 20 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:15
    container_name: instagram_bot_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - instagram-bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    # افزودن پارامترهای پایداری بیشتر
    command: postgres -c shared_buffers=256MB -c max_connections=200

networks:
  instagram-bot-network:
    driver: bridge

volumes:
  postgres_data: