version: '3.8'

services:
  app:
    build: .
    container_name: instagram_bot
    restart: always
    volumes:
      - .:/app
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      postgres:
        condition: service_healthy  # منتظر بماند تا postgres سالم باشد
    networks:
      - instagram-bot-network
    # افزودن تاخیر برای اطمینان بیشتر
    command: >
      bash -c "sleep 10 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  postgres:
    image: postgres:15
    container_name: instagram_bot_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - instagram-bot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s  # زمان بیشتر برای راه‌اندازی اولیه

networks:
  instagram-bot-network:
    driver: bridge

volumes:
  postgres_data: